### ISSUE TITLE
Service is not available after upgrading extension to version 4.0.0

### ISSUE THREAD

**Issue by instruccionesaldorso** [cobwebch/svconnector_csv#12]
TYPO3 11.5.26
PHP 7.4
EXT:svconnector_csv 4.0.0

The next line to get the CSV service returns `false`, after upgrading the extension from version 3.0.0 to version 4.0.0:

```
$services = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::findService('connector', 'csv');
```

I just tried to upgrade PHP to 8.1 locally, but same result.

Is there anything we should use? Official doc doesn't mention anything special that changed from one version to the next one:  https://docs.typo3.org/p/cobweb/svconnector_csv/main/en-us/Developer/Index.html

**Comment by fsuter** [comment]
Oh, my bad! I have forgotten to update that part of the documentation. Indeed things have changed completely, since the TYPO3 Core has deprecated (and removed in v12) the Services architecture.

To get the service, you should now use:
```php
$registry = GeneralUtility::makeInstance(\Cobweb\Svconnector\Registry\ConnectorRegistry::class);
$service = $registry->getServiceForType($key);
```

The connector service API has changed too, please check: https://docs.typo3.org/p/cobweb/svconnector/5.0/en-us/Developers/ConnectorApi/Index.html

**Comment by instruccionesaldorso** [comment]
Sorry, I forgot to reply.
Thanks, working like a charm!
